apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: forgerock
  name: forgerock-service
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    run: forgerock
  type: NodePort
status:
  loadBalancer: {}
